/* Configure the Formspree endpoint after creating a form in your Formspree account.
   Example: 'https://formspree.io/f/abcdefgh'. DO NOT put secrets here. */
const FORMSPREE_ENDPOINT = 'https://formspree.io/f/maeqobbp';
const menu=document.getElementById('menuBtn'); const nav=document.getElementById('nav');
menu.addEventListener('click',()=>{const opened=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(opened));});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}));
document.getElementById('year').textContent=new Date().getFullYear();
const service=document.getElementById('service'),destinationField=document.getElementById('destinationField'),destinationZip=document.getElementById('destinationZip');
function updateService(){const different=service.value==='different_locations';destinationField.hidden=!different;destinationZip.required=different;if(!different)destinationZip.value='';calc();}
service.addEventListener('change',updateService);
const form=document.getElementById('quoteForm'), hours=document.getElementById('hours'), stairs=document.getElementById('stairs'), specialty=document.getElementById('specialty');
function calc(){const h=Number(hours.value),s=Number(stairs.value),twoLocations=service.value==='different_locations',custom=s>=3||specialty.checked||twoLocations;const price=h*85+s*25;document.getElementById('total').textContent=custom?'Custom quote':'$'+price.toFixed(price%1?2:0);document.getElementById('calculation').textContent=custom?(twoLocations?'Multiple sites: labor base only; custom review required':'We’ll review stairs and/or specialty items'):`${h} hours × $85 + $${s*25} stairs`;document.getElementById('estimateNote').textContent=custom?(twoLocations?'You arrange transportation. Travel between locations, crew logistics, stairs and specialty fees are not included; we will confirm a custom quote.':'Base labor before any custom specialty, additional stair, travel, or access charges.'):'Planning estimate only. May exclude travel, access, heavy-item and other charges. Final price requires review.';const serviceLabel=service.options[service.selectedIndex].text;document.getElementById('estimateField').value=custom?`Custom review required; labor base $${h*85}; service ${serviceLabel}; unloading ZIP ${destinationZip.value||'not supplied'}`:`$${price} preliminary estimate`;}
[hours,stairs,specialty].forEach(e=>e.addEventListener('change',calc));updateService();
const date=document.getElementById('date');date.min=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
form.addEventListener('submit',async ev=>{ev.preventDefault();const status=document.getElementById('formStatus');status.textContent='';if(!form.reportValidity())return;if(!FORMSPREE_ENDPOINT){status.textContent='Quote submissions are not connected yet. Site owner: add your Formspree endpoint in script.js before launching. No information has been sent.';status.style.color='#8e263b';return;}const btn=document.getElementById('submitBtn');btn.disabled=true;btn.textContent='Sending…';try{let body=new FormData(form);body.append('subject','New GoodBull labor-only estimate request'); body.append('_subject','New GoodBull labor-only estimate request');const res=await fetch(FORMSPREE_ENDPOINT,{method:'POST',body,headers:{Accept:'application/json'}});if(!res.ok)throw new Error('Form request unsuccessful');status.textContent='Your quote request has been sent! We will review the details and get back to you.';status.style.color='#176038';form.reset();updateService();}catch(err){status.textContent='Could not send your request. Please try again later.';status.style.color='#8e263b';}finally{btn.disabled=false;btn.textContent='Request my quote ↗';}});
